### ISSUE TITLE
Change the repo description

### ISSUE THREAD

**Issue by tutnes** [dynaTrace/Dynatrace-Slack-Integration-Plugin#3]
Hi @ingohackl could you maybe change the repo description? 
![image](https://cloud.githubusercontent.com/assets/5365042/15010122/c1e7cc96-11ea-11e6-8dc9-32e7e0ee7516.png)

**Comment by ingohackl** [comment]
Should I add a link to the website (https://community.dynatrace.com/community/display/DL/Slack+Integration+Plugin) like this is done for other plugins?

**Comment by tutnes** [comment]
Yes thank you. And this as the text above the link:
SlackChat integration for Dynatrace This integration works via WebHooks for Slack
